### ISSUE TITLE
lc teardown not removing user-defined networks

### ISSUE THREAD

**Issue by paulcichonski** [cisco/elsy#5]
Version:

```
lc --version
lc version 1.2.1 (build: 1173ec7614975ce4666463731204b63b3f6095c3)
```

Given the following `lc.yml`:

```
project_name: sample
```

and `docker-compose.yml`:

```
version: '2'
services:
  blackbox-test:
    image: alpine
    command: /bin/true
```

Running `lc ci` will create the following network:

```
$ docker network ls
5d21e2e46f96        sample_default         bridge
```

It is expected that `lc teardown` would remove this network, but it does not. This is bad because if a user tries to later edit the `ipam` config for the network it will not be applied since the network is already created.
