### ISSUE TITLE
Docker-compose format version support

### ISSUE THREAD

**Issue by bstuder** [cisco/elsy#90]
It would be great to have support for minor version of the docker-compose template format, specifically `2.1` to get `HEALTHCHECK` / `condition: service_healthy` facilities which are very useful in general and even more when dealing witch services with warmup condition and/or post-start configs.

**Comment by bstuder** [comment]
@lomigmegard

**Comment by paulcichonski** [comment]
Hey @bstuder, nothing in elsy should prevent you from using 2.1 constructs. 

## Working Example

Here is an example using `lc version v3.1.1 (build: e20228d24e97f69c89def5044830e737d5c1eefc)`:

With a `docker-compose.yml`:

```
version: '2.1'
services:
  test-client:
    image: alpine:latest
    depends_on:
      frontend:
        condition: service_healthy
    command: ["/bin/echo", "started"]
  frontend:
    build: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
```

For the `build: nginx`, I have a local folder that has a `Dockerfile` that is based on `nginx:stable`, and adds `curl` so the healthcheck will work:

```
$ cat nginx/Dockerfile
FROM nginx:stable

RUN apt-get update && apt-get install -y curl
```

With the above everything works as expected:

```
$ lc bootstrap
$ lc dc up test-client
Recreating testhealth_frontend_1 ...
Recreating testhealth_frontend_1 ... done
Recreating testhealth_test-client_1 ...
Recreating testhealth_test-client_1 ... done
Attaching to testhealth_test-client_1
test-client_1  | started
testhealth_test-client_1 exited with code 0
```

If I change the healthceck so that it will not pass:

```
version: '2.1'
services:
  test-client:
    image: alpine:latest
    depends_on:
      frontend:
        condition: service_healthy
    command: ["/bin/echo", "started"]
  frontend:
    build: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181"]
      interval: 1s

```

You can see things fail as expected:

```
$ lc dc up test-client
Creating network "testhealth_default" with the default driver
Creating testhealth_frontend_1 ...
Creating testhealth_frontend_1 ... done

ERROR: for test-client  Container "0a05bc4cc8cb" is unhealthy.
ERROR: Encountered errors while bringing up the project.
ERRO[0006] exit status 1
ERRO[0006] command failed. use --debug to see full stacktrace
```

## Caveats

Note that `healthcheck` and `condition: service_healthy` directives only work when doing a `docker-compose up`, not `docker-compose run`: https://github.com/docker/compose/issues/4369. So if you are doing something like `lc blackbox-test` (which [under the hood leverages docker-compose run](https://github.com/cisco/elsy/blob/master/command/blackboxtest.go#L41-L45)) the conditions won't be respected. For cases like that I recommend using a some test directive that ensures services are healthy before starting test. Here are some examples of that:

* An [example gherkin step for checking service health](https://github.com/cisco/elsy/blob/master/examples/java-note-service/blackbox-test/features/notes.feature#L5), and the [corresponding implementation](https://github.com/cisco/elsy/blob/master/examples/java-note-service/blackbox-test/steps/note_steps.rb#L15-L20) that hits an http healthcheck endpoint
* An [example gherkin step checking service is listening on port 80](https://github.com/cisco/elsy/blob/master/examples/emberjs-ui/blackbox-test/features/service.feature#L18) and the [corresponding implementation](https://github.com/cisco/elsy/blob/master/examples/emberjs-ui/blackbox-test/steps/service_steps.rb#L15-L20) using `nc`.
